[package]
name = "my_kernel"
version = "0.1.0"
edition = "2021"

# Используем новый bootloader вместо старого
[dependencies]
bootloader_api = "0.11.3"
spin = "0.9.8"
x86_64 = "0.14.10"
uart_16550 = "0.3.0"

# Главной бинарный крейт
[[bin]]
name = "my_kernel"
test = false